spring:
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小

#FastDFS
fdfs:
  # socket 连接超时时长
  soTimeout: 1500
  # 连接tracker 服务器超时时长
  connectTimeout: 600
  pool:
    # 从池中借出的对象的最大数目
    max-total: 153
    # 获取连接时的最大等待毫秒数100
    max-wait-millis: 102
  # 缩略图生成参数，可选
  thumbImage:
    width: 150
    height: 150
  # 踪迹服务器tracker_server 请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList:
    - vm.cn:22122
  # 存储服务器storage_server访问地址
  web-server-url: http://vm.cn/